### ISSUE TITLE
Use BMA456 as Activity tracker

### ISSUE THREAD

**Issue by livein21st** [Seeed-Studio/Seeed_BMA456#1]
Hi,

I'm developing a wearable device which will trigger a vibration if the user is inactive/stil for a particular time. 

is it possible to develop with this library? can you show me the demo?

Components in my prototype 

1) Seeduino Grove - Step Counter
2) Seeduino Lotus v1.1

Thank you

**Comment by Cincinnatu** [comment]
It's pretty simple. The example code 'data_raw' demonstrates how to get the acceleration values in the x, y, and z directions from the sensor. You can use this data to achieve the required functionality.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
