### ISSUE TITLE
Not working with ESP32

### ISSUE THREAD

**Issue by Nafihahmd** [Seeed-Studio/Seeed_BMA456#2]
I am compiling the step_counter example. The counter is never incrementing.

Using ESP32 Dev kit v2 and Arduino IDE

**Comment by Cincinnatu** [comment]
Is the issue still present? If it is, please provide more debugging information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
