### ISSUE TITLE
M5Stackで動作させれない

### ISSUE THREAD

**Issue by ep22074** [Seeed-Studio/Seeed_BMA456#3]
サンプルコードを改良してstepをM5Stackで表示させようとしたができなかった。
#include <M5Stack.h>
#include "arduino_bma456.h"

uint32_t step = 0;

void setup(void) {
    M5.begin();
    M5.Power.begin();
    Serial.begin(115200);
    Serial.println("BMA456 Step Counter");

    bma456.initialize(RANGE_4G, ODR_1600_HZ, NORMAL_AVG4, CONTINUOUS);
    bma456.stepCounterEnable();
    M5.Lcd.setTextSize(3);
    M5.Lcd.setCursor(0, 110);
}

void loop(void) {
    M5.update();
    step = bma456.getStepCounterOutput();

    Serial.print("Step: ");
    Serial.println(step);
    M5.Lcd.print(step);
    delay(1000);
}

**Comment by Cincinnatu** [comment]
If this issue still persists, you need to provide more debugging information.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
